plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag
  
header_pages:
  - about.md
  
relative_links:
  enabled: true
  collections: true
remote_theme: jekyll/minima

include:
  - images