plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  
header_pages:
  - about.md
  
relative_links:
  enabled: true
  collections: true
remote_theme: jekyll/minima

google_analytics: G-GVDQPHEWST

include:
  - images
